### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by bigwss** [OmerFarukTutkun/Devre#14]
Devre 5.0
commit: accfe23e5d2a66e09b7c8603bdad2ad353a0aeab
how to make:  make avx2

run info as follows:

Devre  5.0 by Omer Faruk Tutkun
position fen rnbqkbn1/pppppppP/8/8/8/8/PPPPPPP1/RNBQKBNR w KQkq - 0 1
go depth 10
 info depth 1 score cp 1771 pv h7g8q  nps 888 nodes 32 time 36
 info depth 2 score cp 1925 pv h7g8q d7d5  nps 2305 nodes 83 time 36
 info depth 3 score cp 1944 pv h7g8q d7d5 b1c3  nps 5083 nodes 183 time 36
 info depth 4 score cp 1968 pv h7g8q d7d5 b1c3 c8f5  nps 10833 nodes 390 time 36
 info depth 5 score cp 1935 pv h7g8q d7d5 b1c3 c8f5 g2g4  nps 22243 nodes 823 time 37
 info depth 6 score cp 2039 pv h7g8q e7e5 h1h3 d7d5 g8h7 c8h3  nps 54552 nodes 2073 time 38
 info depth 7 score cp 2039 pv h7g8q e7e5 h1h3 d7d5 g8h7 c8h3 h7h3  nps 60526 nodes 2300 time 38
 info depth 8 score cp 2023 pv h7g8q e7e5 h1h3 d7d5 g8h7 c8h3 h7h3 f8b4  nps 71743 nodes 2798 time 39
[1]    149788 segmentation fault  ./devre

It seems that certain fens can cause the program to crash.
Or is there something wrong with how I use it?

**Comment by OmerFarukTutkun** [comment]
Thanks for reporting. 

Fen is not valid as it says black can castle both side but actually king side castling is not possible. I don't know the problem is about that. I will look at it.

**Comment by bigwss** [comment]
thanks a lot. 
it is "FEN is not valid". 
I change FEN to  "rnbqkbn1/pppppppP/8/8/8/8/PPPPPPP1/RNBQKBNR w KQq - 0 1"  works.
