### ISSUE TITLE
function isMaterialDraw

### ISSUE THREAD

**Issue by bigwss** [OmerFarukTutkun/Devre#15]
This FEN "8/4K3/2k5/8/3b4/2n5/4n3/8 b - - 1 2"  will return true

I think there are some problems with the implementation of this function

As far as I know, there are 4 situations where it is definitely a draw.

1. Both sides only have a single king left
2. One side only has a single king left, and the other side only has a king and a single knight.
3. One side only has a single king left, and the other side only has a king and a single bishop.
4. Both sides only have a single king  and a bishop of in same color grid. 

The following is a possible code implementation:

bool Board::isMaterialDraw()
{
    if (bitboards[WHITE_PAWN] || bitboards[BLACK_PAWN] || bitboards[WHITE_ROOK] ||
        bitboards[BLACK_ROOK] || bitboards[WHITE_QUEEN] || bitboards[BLACK_QUEEN])
        return false;
    if (popcount64(occupied[0] | occupied[1]) < 4) {
        // here only left: K v K, K+B v K, K+N v K.
        return true;
    }
    if (popcount64(bitboards[WHITE_KNIGHT] | bitboards[BLACK_KNIGHT]) != 0) {
        return false;
    }
    if (popcount64(occupied[0] | occupied[1]) == 4) {
        constexpr uint64_t kWhiteSquares(0x55AA55AA55AA55AAULL);
        constexpr uint64_t kBlackSquares(0xAA55AA55AA55AA55ULL);
        if (bitboards[WHITE_BISHOP] && bitboards[BLACK_BISHOP]) {
            return !(((bitboards[WHITE_BISHOP] | bitboards[BLACK_BISHOP]) & kWhiteSquares) &&
                     ((bitboards[WHITE_BISHOP] | bitboards[BLACK_BISHOP]) & kBlackSquares));
        }
    }
    return false;
}

**Comment by OmerFarukTutkun** [comment]
Yes you are right it seems i broke this function when going from C to C++. 
Thank you so much for the detailed explanation, I will fix it as you suggested.
