### ISSUE TITLE
Network for sse3 - question

### ISSUE THREAD

**Issue by rwbc** [OmerFarukTutkun/Devre#4]
Is this really for sse3 or is it a typo and you meant ssse3?
I am asking because I compiled Devre for a friend from talkchess, for which I always have to use `march=amdfam10`,
but he says the compilation doesn't run for him (this is the first time ever...)

```
https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html

‘amdfam10’
‘barcelona’

 CPUs based on AMD Family 10h cores with x86-64 instruction set support. (This supersets MMX, SSE, SSE2, SSE3, SSE4A, 3DNow!, enhanced 3DNow!, ABM and 64-bit instruction set extensions.)

```
The compendium at gcc says amdfam10 hardware supports sse3 (but not ssse3).

BTW I had no problem to compile for my own hardware since your change (old core2 supporting up to sse4.1 but no popcnt).

Guenther (RWBC)

**Comment by OmerFarukTutkun** [comment]
It is really for SSE3 , I didn't use anything from ssse3. I tried to compile with march=amdfam10, it compiles and runs without problem on my laptop.
