### ISSUE TITLE
Request for Clarification or Addition of License Statement in Your Project

### ISSUE THREAD

**Issue by wavejava** [OmerFarukTutkun/Devre#46]
Dear OmerFarukTutkun，

Thank you for your outstanding projects, such as Devre. Your work represents a valuable contribution to open-source communication.

We recently discovered an Unlicense statement in incbin, and we are uncertain whether it pertains to your work. 

Could you please clarify this matter? Additionally, we kindly request that you add a license statement, such as BSD or MIT (as attached), or any other license of your preference, to your project.

Thank you for your attention to this matter.

Best regards,

wavejava

**Comment by wavejava** [comment]
[MIT.txt](https://github.com/user-attachments/files/16972824/MIT.txt)
[BSD.txt](https://github.com/user-attachments/files/16972825/BSD.txt)
 BSD & MIT statement file for your reference .

**Comment by OmerFarukTutkun** [comment]
incbin.h and Unlicense files were taken from https://github.com/graphitemaster/incbin .

Thanks for the advice, I will add GPL license.
