### ISSUE TITLE
Well done.

### ISSUE THREAD

**Issue by SzotsGabor** [OmerFarukTutkun/Devre#8]
"I couldn't make much progress. This version is 100 elo stronger than the previous one"

So +100 is not much for you. Then we may expect big things from Devre in the future. Keep up the good work, Ömer.

Best regards,
Gabor Szots
CCRL testing group

**Comment by OmerFarukTutkun** [comment]
thanks:smiley::smiley:, Developing a chess engine is fun and addictive for me. I will continue to develop my engine with my best.  My goal is to beat stockfish 8(it was the strongest chess engine when I started playing chess), I'm ~200 elo behind my goal. Hope I will gain more ELO in the future, and make my goal come true
